"""initial schema: users, locations, satellite_cache, predictions, argo_profiles, cyclone_events, generated_reports

Revision ID: 0001
Revises:
Create Date: 2026-09-10

Hand-written (not autogenerated, since this sandbox has no live Postgres to
run `alembic revision --autogenerate` against) to exactly match
app/database/models.py. Verify with `alembic check` once you have a real DB.
"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")

    op.create_table(
        "users",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("email", sa.String(255), unique=True, index=True, nullable=False),
        sa.Column("hashed_password", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "locations",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("label", sa.String(255), nullable=False),
        sa.Column("region_key", sa.String(64), index=True, nullable=False),
        sa.Column("geom", geoalchemy2.Geometry(geometry_type="POINT", srid=4326)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_locations_geom", "locations", ["geom"], postgresql_using="gist")

    op.create_table(
        "satellite_cache",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("source", sa.String(128), index=True, nullable=False),
        sa.Column("cache_key", sa.String(255), index=True, nullable=False),
        sa.Column("status", sa.String(16), nullable=False),
        sa.Column("resolution", sa.String(64)),
        sa.Column("confidence", sa.String(16)),
        sa.Column("payload", sa.JSON),
        sa.Column("fetched_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
    )

    op.create_table(
        "predictions",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("region_key", sa.String(64), index=True, nullable=False),
        sa.Column("geom", geoalchemy2.Geometry(geometry_type="POINT", srid=4326)),
        sa.Column("valid_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("depths_m", sa.JSON),
        sa.Column("temperature_c", sa.JSON),
        sa.Column("uncertainty_c", sa.JSON),
        sa.Column("confidence", sa.String(16)),
        sa.Column("model_version", sa.String(64)),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_index("ix_predictions_geom", "predictions", ["geom"], postgresql_using="gist")

    op.create_table(
        "argo_profiles",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("platform_number", sa.String(32), index=True, nullable=False),
        sa.Column("cycle_number", sa.Integer, nullable=False),
        sa.Column("geom", geoalchemy2.Geometry(geometry_type="POINT", srid=4326)),
        sa.Column("profile_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("temperature_profile", sa.JSON),
        sa.Column("salinity_profile", sa.JSON),
        sa.Column("pressure_levels_db", sa.JSON),
        sa.Column("position_qc", sa.Integer),
        sa.Column("source", sa.String(64), server_default="Argo GDAC (via Argovis)"),
    )
    op.create_index("ix_argo_profiles_geom", "argo_profiles", ["geom"], postgresql_using="gist")

    op.create_table(
        "cyclone_events",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("storm_name", sa.String(128), nullable=False),
        sa.Column("basin", sa.String(64), index=True, nullable=False),
        sa.Column("category", sa.String(32)),
        sa.Column("track", sa.JSON),
        sa.Column("warm_core_regions", sa.JSON, nullable=True),
        sa.Column("subsurface_heat_reservoir_j_m2", sa.Float, nullable=True),
        sa.Column("source", sa.String(64)),
        sa.Column("last_updated", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )

    op.create_table(
        "generated_reports",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("user_id", sa.Integer, sa.ForeignKey("users.id"), nullable=True),
        sa.Column("region_key", sa.String(64), nullable=False),
        sa.Column("lat", sa.Float, nullable=True),
        sa.Column("lon", sa.Float, nullable=True),
        sa.Column("file_path", sa.String(512), nullable=False),
        sa.Column("sources_used", sa.JSON),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("generated_reports")
    op.drop_table("cyclone_events")
    op.drop_index("ix_argo_profiles_geom", table_name="argo_profiles")
    op.drop_table("argo_profiles")
    op.drop_index("ix_predictions_geom", table_name="predictions")
    op.drop_table("predictions")
    op.drop_table("satellite_cache")
    op.drop_index("ix_locations_geom", table_name="locations")
    op.drop_table("locations")
    op.drop_table("users")
